### ISSUE TITLE
Placeholder prop

### ISSUE THREAD

**Issue by lucasvallenet** [desislavsd/vue-select#10]
Could you add a placeholder prop to change the default 'Search..' when no value is selected ?

Thank you

**Comment by desislavsd** [comment]
As stated in the beginning of the [props page](https://desislavsd.gitbook.io/vue-select/props) in the docs:
> The vSelect component does not inherit attributes and all additional attributes are directly passed to the internal input element

So you can freely pass `placeholder` and all other valid input attributes.
