### ISSUE TITLE
Can I close the option list on clicking already selected item?

### ISSUE THREAD

**Issue by ishiki-arata** [desislavsd/vue-select#17]
Hello, I am wondering if there is a way to make the list close also when I click on an already selected item? Right now it does nothing and I have to click outside of the dropdown to close it.

Thank you!

**Comment by desislavsd** [comment]
Yes, you can achieve that in a few ways. As you can find in the [docs](https://desislavsd.gitbook.io/vue-select/events) the `select` event is always fired. Therefore you can do something like this:
```html
<v-select ref="mySelect" @select="$refs.mySelect.close()" ... />
```
Another more general approach would be to extend the vSelect component during setup with additional prop to control whether to always close the dropdown. The solution would look something like this:
```javascript
Vue.use(VueSelect, {
    name: 'vSelect',
    mixin: {
        props: {

            // register custom boolean prop
            alwaysCloseOnSelect: Boolean
        },

        mounted(){

            // add listener for the select event
            this.$on("select", () => {
                
              // close if alwaysCloseOnSelect is set to true
              if (this.alwaysCloseOnSelect) this.close();
            });
        }
    }
})
```
which then will be used like:
```html
<my-select always-close-on-select   ... />
```
Ofc, you can also do the same in the case of local registration:
```html
<template>
    <v-select always-close-on-select   ... />
</template>
<script>
    import { vSelect } from "@desislavsd/vue-select";

    let MySelect = {
        mixins: [vSelect],
        props: { /* ... */ },
        mounted(){
            /* ... */
        }
    }

    export default {
        components: { MySelect },
    };
</script>
```

**Comment by ishiki-arata** [comment]
Thank you very much for the reply and thanks for this great select! :)
