### ISSUE TITLE
Error Cannot read property 'value' of undefined

### ISSUE THREAD

**Issue by ishiki-arata** [desislavsd/vue-select#19]
Is there a way to disable the X which removes the selection?
Or maybe I am doing something wrong, I just can't get around to fixing this issue.

I have a list of options, when I select something it works fine, but if I click on X to remove selections, when I click submit i get this error cannot read property 'value' of undefined.

**Comment by desislavsd** [comment]
@ishiki-arata This problem doesn't sound like its related to the clear button. You can try to remove it from the devtools first and check if the form submission still triggers the error. My guess is your v-model is set to an object after selection and in your submit handler you are trying to access the `value` property of that object. But if there is nothing selected `yourObj.value` will trigger an error as `yourObj` is `undefined`. Therefore you must first check  if it is set before trying to access its properties.

**Comment by ishiki-arata** [comment]
`<v-select v-model="orderDate.currency" as="name::lbl" :from="orderDateOptions" @select="$refs.orderdate.close()" ref="orderdate" type="text"> 
              <template v-slot:option="{ option }">
              <div class="select-option-width" v-on:click="dirtyForm">{{ option.value.name }}</div>
            </template>
            </v-select> `
`orderDate: {
                currency: ''
            },
      orderDateOptions: [
                    { name: 'Anytime', value: 'anytime', lbl: 'at-orderdate' },
                  { name: 'Today', value: 'today', lbl: 't-orderdate' },
                  { name: 'Yesterday', value: 'yesterday', lbl: 'y-orderdate' },
                  { name: 'Last 7 Days', value: 'last7d', lbl: '7d-orderdate' },
                  { name: 'Last 30 Days', value: 'last30d', lbl: '30d-orderdate' },
                  { name: 'This Month', value: 'thism', lbl: 'm-orderdate' },
                  { name: 'Previous Month', value: 'prevm', lbl: 'prevm-orderdate' },
                  { name: 'Last 12 Months', value: 'last12m', lbl: '12m-orderdate' },
                  
                  { name: 'Custom', value: 'custom', lbl: 'c-orderdate' },
      ],`

this is the code for my select. I tried putting one of the select objects in orderDate.currency, which starts it off with that selection. But if I click the X it gives me value error. Is there a way to use a selected object as the default selection when you click on X? Or how should I go around this.

Thank you!

**Comment by ishiki-arata** [comment]
Indeed, the error does NOT trigger when I click submit, it triggers the moment I click the clear button. This is why I assumed it's an error form the V-select component

**Comment by desislavsd** [comment]
Hm, this is a bit strange. Try to put in your `<template>` `{{ option ? option.value.name : '' }}`. 

If it doesn't help, the easiest way to hide the button is with CSS. Otherwise you would have to provide [custom layout](https://desislavsd.gitbook.io/vue-select/layout-and-theming) and remove the `actions` slot but this is a bit advanced. 

> Is there a way to use a selected object as the default selection when you click on X?

Yes you can, you can intercept the model update by replacing the `v-model` syntax with its [longer alternative](https://vuejs.org/v2/guide/components.html?#Using-v-model-on-Components):

```html
<v-select :value="orderDate.currency" @input="orderDate.currency = $event || defaultCurrency" ... />
```

**Comment by ishiki-arata** [comment]
<v-select :value="orderDate.currency" @input="orderDate.currency = $event || defaultCurrency" ... />

This works, solved my issues.

Thank you very much for the fast help!
