### ISSUE TITLE
displays value instead of label if set programmatically

### ISSUE THREAD

**Issue by nklatt** [desislavsd/vue-select#7]
If a v-select is set up and the attribute it is v-model associated with is changed, it displays the value instead of the label until the v-select element is clicked, then it updates to properly display the label.

This fiddle demonstrates the issue:

https://jsfiddle.net/mevj407u/

(Thanks for the great component!)

**Comment by desislavsd** [comment]
Yes @nklatt , I am familiar with this issue, but its a bit tricky to deal with this use case. I will try to fix it as soon as I can. Thanks!

**Comment by desislavsd** [comment]
@nklatt I just updated the package. It should now be OK. I am closing the Issue. Thanks for reporting and If you encounter any other problems you are welcome.

**Comment by nklatt** [comment]
Seems to be working for me - thanks so much for the update!
